[package]
name = "fifo"
version = "0.10.0"
authors = ["Heinz N. Gies <heinz@project-fifo.net>"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
rustc-serialize = "0.3"
clap = "~2.16.1"
prettytable-rs = "^0.6"
libc = "0.2"
