use clap::{App, Arg, SubCommand};
pub fn build_cli() -> App<'static, 'static> {
    App::new("fifo")
        .arg(Arg::with_name("file")
             .help("Some input file"))
        .arg(Arg::with_name("config")
             .short("c")
             .long("config")
             .takes_value(true)
             .value_name("FILE")
             .help("Optionally use some config file"))
        .arg(Arg::with_name("verbose")
             .short("v")
             .long("verbose")
             .help("Output verbose information"))
        .subcommand(SubCommand::with_name("test")
                    .about("Tests things for us...")
                    .arg(Arg::with_name("totest")
                         .long("thing")
                         .help("The thing to test")
                         .takes_value(true)
                         .possible_values(&["thing1", "other-thing", "stuff"])))
}
